const practiceAreas=['Derecho Civil','Derecho Laboral','Derecho Comercial','Daños y Perjuicios','Contratos','Sucesiones','Mediación','Asesoramiento Empresarial'];
const advantages=['Experiencia','Compromiso','Respuesta rápida','Atención personalizada','Transparencia','Excelencia profesional'];
const posts=[['img/blog-1.svg','12 Jun 2026','Claves para prevenir conflictos contractuales'],['img/blog-2.svg','28 May 2026','Aspectos esenciales de una mediación efectiva'],['img/blog-3.svg','09 May 2026','Buenas prácticas legales para empresas en crecimiento']];
const testimonials=[['La atención fue impecable, clara y muy humana. Nos guiaron con seguridad en todo el proceso.','Cliente particular'],['Encontramos un equipo estratégico y comprometido con las necesidades de nuestra empresa.','Dirección de PyME'],['Excelente comunicación, transparencia y resultados. Volveríamos a elegirlos.','Cliente corporativo']];
const icon='<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v18"/><path d="M5 7h14"/><path d="M6 7l-3 6h6L6 7Z"/><path d="M18 7l-3 6h6l-3-6Z"/><path d="M8 21h8"/></svg>';
const qs=(s,p=document)=>p.querySelector(s);const qsa=(s,p=document)=>[...p.querySelectorAll(s)];
function card(title,text){return `<article class="practice-card reveal">${icon}<h3>${title}</h3><p>${text}</p></article>`}
qs('.practice-grid').innerHTML=practiceAreas.map(a=>card(a,'Abordaje preventivo y contencioso con análisis estratégico, comunicación clara y seguimiento permanente.')).join('');
qs('.why-grid').innerHTML=advantages.map(a=>`<article class="why-card reveal">${icon}<h3>${a}</h3><p>Procesos ordenados, criterios profesionales y acompañamiento cercano en cada etapa.</p></article>`).join('');
qs('.blog-grid').innerHTML=posts.map(p=>`<article class="blog-card reveal"><img src="${p[0]}" alt="Imagen editorial sobre ${p[2]}"><div><time>${p[1]}</time><h3>${p[2]}</h3><p>Una mirada práctica para tomar mejores decisiones legales.</p><a href="#contacto">Leer más</a></div></article>`).join('');
let current=0;function renderTestimonial(){const t=testimonials[current];qs('[data-slider]').innerHTML=`<article class="testimonial-card"><p class="stars">★★★★★</p><blockquote>“${t[0]}”</blockquote><strong>${t[1]}</strong></article>`;current=(current+1)%testimonials.length}renderTestimonial();setInterval(renderTestimonial,4500);
const header=qs('[data-header]'),toggle=qs('[data-nav-toggle]'),menu=qs('[data-nav-menu]');
function onScroll(){header.classList.toggle('scrolled',scrollY>40);document.documentElement.style.setProperty('--scroll',scrollY)}addEventListener('scroll',onScroll,{passive:true});onScroll();
toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.classList.toggle('active',open);toggle.setAttribute('aria-expanded',open)});qsa('.nav-menu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.classList.remove('active');toggle.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.16});qsa('.reveal,.reveal-left,.reveal-right').forEach(el=>observer.observe(el));
const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=+el.dataset.counter;let n=0;const step=Math.max(1,Math.ceil(end/70));const timer=setInterval(()=>{n+=step;el.textContent=n>=end?end:n;if(n>=end)clearInterval(timer)},22);counterObserver.unobserve(el)}),{threshold:.8});qsa('[data-counter]').forEach(el=>counterObserver.observe(el));
qs('[data-year]').textContent=new Date().getFullYear();qs('.contact-form').addEventListener('submit',e=>{e.preventDefault();qs('[data-form-note]').textContent='Gracias. Su consulta fue registrada para contacto.';e.currentTarget.reset()});
